#!/bin/bash

export PASSENGER_COUNT=200
export FERRY_COUNT=4
export FERRY_CAPACITY=50
export RAMP_CAPACITY_REG=3
export RAMP_CAPACITY_VIP=2
export FERRY_DEPARTURE_INTERVAL=5
export FERRY_TRAVEL_TIME=1
export PASSENGER_SECURITY_TIME_MIN=5
export PASSENGER_SECURITY_TIME_MAX=10
export PASSENGER_BOARDING_TIME=1000
export FERRY_GATE_MAX_DELAY=1000
export FERRY_BAGGAGE_LIMIT_MIN=40
export FERRY_BAGGAGE_LIMIT_MAX=60
export PASSENGER_BAG_WEIGHT_MIN=5
export PASSENGER_BAG_WEIGHT_MAX=50
export DANGEROUS_ITEM_CHANCE=10
export VIP_CHANCE=20

exec "$@"