#!/bin/bash

source tests.shlib

export PASSENGER_COUNT=5000
export FERRY_COUNT=5
export FERRY_CAPACITY=500
export RAMP_CAPACITY_REG=3
export RAMP_CAPACITY_VIP=2

export FERRY_DEPARTURE_INTERVAL=10 #s
export FERRY_TRAVEL_TIME=1 #s
export PASSENGER_SECURITY_TIME_MIN=5 #ms
export PASSENGER_SECURITY_TIME_MAX=10 #ms
export PASSENGER_BOARDING_TIME=1000 #us
export FERRY_GATE_MAX_DELAY=10000 # ms Not more than 1 000 000

export FERRY_BAGGAGE_LIMIT_MIN=50
export FERRY_BAGGAGE_LIMIT_MAX=60
export PASSENGER_BAG_WEIGHT_MIN=5
export PASSENGER_BAG_WEIGHT_MAX=50

export DANGEROUS_ITEM_CHANCE=0
export VIP_CHANCE=0

exec "$@"