#ifndef FERRY_COMMON_CONFIG_H
#define FERRY_COMMON_CONFIG_H

#define PASSENGER_COUNT 10
#define FERRY_COUNT 4
#define SECURITY_STATIONS 3
#define SECURITY_STATION_CAPACITY 2
#define SECURITY_MAX_FRUSTRATION 3
#define FERRY_CAPACITY 50
#define RAMP_CAPACITY 5
#define QUEUE_CAPACITY PASSENGER_COUNT

#define FERRY_DEPARTURE_INTERVAL 30
#define FERRY_TRAVEL_TIME 60
#define PASSENGER_SECURITY_TIME_MIN 2
#define PASSENGER_SECURITY_TIME_MAX 5
#define PASSENGER_BOARDING_TIME 2

#define FERRY_BAGGAGE_LIMIT_MIN 20
#define FERRY_BAGGAGE_LIMIT_MAX 60
#define PASSENGER_BAG_WEIGHT_MIN 5
#define PASSENGER_BAG_WEIGHT_MAX 55

#define LOG_FILE "simulation.log"

#endif