#ifndef FERRY_COMMON_CONFIG_H
#define FERRY_COMMON_CONFIG_H

#define PASSENGER_COUNT 200
#define FERRY_COUNT 5
#define SECURITY_STATIONS 3
#define SECURITY_STATION_CAPACITY 2
#define SECURITY_MAX_FRUSTRATION 3
#define FERRY_CAPACITY 50
#define RAMP_CAPACITY_REG 3
#define RAMP_CAPACITY_VIP 2
#define RAMP_CAPACITY (RAMP_CAPACITY_REG + RAMP_CAPACITY_VIP)
#define QUEUE_CAPACITY PASSENGER_COUNT

#define FERRY_DEPARTURE_INTERVAL 15
#define FERRY_TRAVEL_TIME 30
#define PASSENGER_SECURITY_TIME_MIN 2
#define PASSENGER_SECURITY_TIME_MAX 5
#define PASSENGER_BOARDING_TIME 2
#define FERRY_GATE_MAX_DELAY 8

#define FERRY_BAGGAGE_LIMIT_MIN 20
#define FERRY_BAGGAGE_LIMIT_MAX 60
#define PASSENGER_BAG_WEIGHT_MIN 5
#define PASSENGER_BAG_WEIGHT_MAX 50

#define LOG_FILE "simulation.log"

#endif