#ifndef FERRY_COMMON_CONFIG_H
#define FERRY_COMMON_CONFIG_H

#define PASSENGER_COUNT 100
#define FERRY_COUNT 4
#define SECURITY_STATIONS 3
#define FERRY_CAPACITY 50
#define RAMP_CAPACITY 5

#define FERRY_DEPARTURE_INTERVAL 30
#define FERRY_TRAVEL_TIME 60
#define PASSENGER_SECURITY_TIME 5
#define PASSENGER_BOARDING_TIME 2

#define LOG_FILE "simulation.log"

#endif